/**
 * Ambient type declarations for GWEN virtual modules consumed at browser runtime.
 *
 * These modules are generated by `@gwenjs/vite` and resolved by Vite during bundling.
 * They are never present on disk — TypeScript needs these declarations to type-check
 * any file that imports them.
 */

declare module "virtual:gwen/local-plugins" {
  import type { GwenPlugin } from "@gwenjs/core";

  /** Factories for each file found in `src/plugins/`. Call each factory to get a plugin instance. */
  export const plugins: Array<() => GwenPlugin>;
}

declare module "virtual:gwen/local-modules" {
  import type { GwenModule } from "@gwenjs/schema";

  /** Module definitions found in `src/modules/`, with names inferred from filenames. */
  export const modules: GwenModule[];
}
