/* oxlint-disable no-unused-vars -- type fixture: the checker is the assertion */

import type * as Root from "@gwenjs/schema";

type _0 = [
  Root.AutoImport,
  Root.ComponentLifecycleHooks,
  Root.DeepPartial<never>,
  Root.DisposableRegistryBase,
  Root.EngineAPI,
  Root.EngineLifecycleHooks,
  Root.EntityLifecycleHooks,
  Root.ExtensionLifecycleHooks,
  Root.GwenBaseConfig,
  Root.GwenBuildHooks,
  Root.GwenConfigInput,
  Root.GwenDisposable,
  Root.GwenEngineBase,
  Root.GwenErrorBusBase,
  Root.GwenErrorLevel,
  Root.GwenErrorPayload,
  Root.GwenHookHandler,
  Root.GwenHooks<never>,
  Root.GwenKit,
  Root.GwenLogEntry,
  Root.GwenLogLevel,
  Root.GwenLogger,
  Root.GwenModule,
  Root.GwenModuleDefinition,
  Root.GwenModuleEntry,
  Root.GwenOptions,
  Root.GwenPlugin,
  Root.GwenRuntimeHooks,
  Root.GwenScopeMeta,
  Root.GwenScopeType,
  Root.GwenTypeTemplate,
  Root.HookBusBase,
  Root.IGwenLogProvider,
  Root.IGwenLogger,
  Root.IGwenScope,
  Root.LogEntry,
  Root.LogLevel,
  Root.PluginDeclaration,
  Root.PluginErrorContext,
  Root.PluginLifecycleHooks,
  Root.SceneLifecycleHooks,
  Root.VitePlugin,
  Root.ViteUserConfig,
];
