/**
 * @file gwen:physics3d — Vite plugin for layer inlining and build-time optimizations.
 */
import type { Plugin } from 'vite';
import { createHash } from 'node:crypto';
import { readFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import MagicString from 'magic-string';
import {
  evalBitExpr,
  extractLayerDefinitions,
  inlineLayerReferences,
} from '@gwenjs/vite/shared/layer-utils';

// Re-export for backward compatibility (tests may import from here).
export { evalBitExpr, extractLayerDefinitions, inlineLayerReferences };

/**
 * Options accepted by {@link physics3dVitePlugin}.
 */
export interface GwenPhysics3DPluginOptions {
  /**
   * Log inlining activity to the console when layer constants are replaced.
   * @default false
   */
  debug?: boolean;

  /**
   * Enable BVH pre-baking for `useMeshCollider('./file.glb')` patterns.
   * Requires the `physics3d/build-tools` Node.js WASM to be built first.
   * @default false
   */
  bvhPrebake?: boolean;
}

/**
 * @deprecated Use {@link GwenPhysics3DPluginOptions} instead.
 */
export type Physics3DVitePluginOptions = GwenPhysics3DPluginOptions;

// ─── BVH pre-baking support ───────────────────────────────────────────────────

/** Lazy-loaded build-tools WASM module (Node.js target). */
let buildToolsWasm: {
  build_bvh_from_glb: (bytes: Uint8Array, name?: string) => Uint8Array;
} | null = null;

/**
 * Injectable loader override for build-tools WASM — used in tests to inject a mock
 * without requiring the actual `build-tools/gwen_core.js` binary.
 * @internal
 */
let _buildToolsLoaderOverride:
  | (() => Promise<{
      build_bvh_from_glb: (bytes: Uint8Array, name?: string) => Uint8Array;
    }>)
  | null = null;

/**
 * Set a custom build-tools loader. Call before any `transformBvhReferences` invocation.
 * Clears the module-level cache so the new loader is used on the next call.
 *
 * @param loader - Async factory returning a build-tools-like object.
 *
 * @internal Exported for unit tests only — do not call in production code.
 */
export function _setBuildToolsLoader(
  loader: () => Promise<{
    build_bvh_from_glb: (bytes: Uint8Array, name?: string) => Uint8Array;
  }>,
): void {
  _buildToolsLoaderOverride = loader;
  buildToolsWasm = null; // reset so the new loader is picked up
}

/**
 * Lazily import and initialise the build-tools WASM module.
 * Cached after first call — subsequent calls are instant.
 *
 * @internal
 */
async function getBuildTools(): Promise<{
  build_bvh_from_glb: (bytes: Uint8Array, name?: string) => Uint8Array;
}> {
  if (!buildToolsWasm) {
    if (_buildToolsLoaderOverride) {
      buildToolsWasm = await _buildToolsLoaderOverride();
    } else {
      // @ts-ignore — build-tools/gwen_core.js is generated by scripts/build-wasm.sh
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const mod = (await import('../build-tools/gwen_core')) as any;
      await mod.default?.();
      buildToolsWasm = mod as typeof buildToolsWasm;
    }
  }
  return buildToolsWasm!;
}

/**
 * Regex matching `useMeshCollider` or `useConvexCollider` calls whose first
 * argument is a relative `.glb` string literal.
 *
 * Captures:
 *   1. Quote character used
 *   2. The GLB relative path (e.g. `./terrain.glb`)
 *   3. Optional `, { mesh: '...' }` options tail
 *
 * @internal
 */
const MESH_GLB_RE =
  /use(?:Mesh|Convex)Collider\(\s*(['"`])(\.\/[^'"` \n]+\.glb)\1(\s*,\s*\{[^}]*\})?\s*\)/g;

/**
 * Detect `useMeshCollider('./file.glb')` patterns and pre-bake their BVH.
 * Returns the transformed code string, or `null` if no matches were found.
 *
 * @param code - Source file contents to scan and transform.
 * @param id - Absolute path of the source file (used to resolve relative GLB paths).
 * @param emitFile - Optional Rollup `emitFile` callback for writing the BVH asset.
 * @returns Transformed source string, or `null` when no GLB patterns were found.
 *
 * @internal Exported for the Vite plugin and unit tests.
 */
export async function transformBvhReferences(
  code: string,
  id: string,
  emitFile?: (opts: { type: 'asset'; name: string; source: Buffer }) => string,
): Promise<string | null> {
  MESH_GLB_RE.lastIndex = 0;
  if (!MESH_GLB_RE.test(code)) return null;
  MESH_GLB_RE.lastIndex = 0;

  const tools = await getBuildTools();
  let transformed = code;
  let offset = 0;

  for (const match of code.matchAll(MESH_GLB_RE)) {
    const [full, , glbPath, optionsStr] = match;
    const absGlbPath = resolve(dirname(id), glbPath);

    if (!existsSync(absGlbPath)) {
      console.warn(`[gwen:physics3d] useMeshCollider: file not found: ${absGlbPath}`);
      continue;
    }

    const meshNameMatch = optionsStr?.match(/mesh\s*:\s*['"`]([^'"` ]+)['"`]/);
    const meshName = meshNameMatch?.[1];

    const glbBytes = readFileSync(absGlbPath);
    let bvhBuffer: Uint8Array;
    try {
      bvhBuffer = tools.build_bvh_from_glb(new Uint8Array(glbBytes), meshName);
    } catch (e) {
      console.warn(`[gwen:physics3d] BVH pre-bake failed for ${glbPath}: ${e}`);
      continue;
    }

    const hash = createHash('md5').update(bvhBuffer).digest('hex').slice(0, 8);
    const assetName = `bvh-${hash}.bin`;

    if (emitFile) {
      emitFile({ type: 'asset', name: assetName, source: Buffer.from(bvhBuffer) });
    }

    const replacement = `useMeshCollider({ __bvhUrl: '${assetName}' })`;
    const start = (match.index ?? 0) + offset;
    transformed =
      transformed.slice(0, start) + replacement + transformed.slice(start + full.length);
    offset += replacement.length - full.length;
  }

  return transformed !== code ? transformed : null;
}

/**
 * `gwen:physics3d` — Vite plugin for Physics 3D build-time optimizations.
 *
 * Performs the following transformations:
 * - **Layer inlining**: replaces `Layers.player` references (from a `defineLayers()`
 *   call) with their literal bitmask values, enabling dead-code elimination in
 *   optimised builds.
 * - **BVH pre-baking** (opt-in via `bvhPrebake: true`): detects `useMeshCollider('./file.glb')`
 *   patterns and replaces them with pre-baked `{ __bvhUrl: 'bvh-<hash>.bin' }` references
 *   at build time.
 *
 * Registered automatically by the `physics3dModule` when added to the GWEN config.
 * Can also be added manually to a plain Vite config:
 *
 * @example
 * ```typescript
 * // vite.config.ts
 * import { physics3dVitePlugin } from '@gwenjs/physics3d'
 *
 * export default {
 *   plugins: [physics3dVitePlugin({ debug: true, bvhPrebake: true })],
 * }
 * ```
 *
 * @param options - Plugin options.
 * @returns A Vite {@link Plugin} object.
 *
 * @since 1.0.0
 */
export function physics3dVitePlugin(options: GwenPhysics3DPluginOptions = {}): Plugin & {
  /** @internal Exposed for unit tests. */
  transformBvhReferences: typeof transformBvhReferences;
} {
  const { bvhPrebake = false, ...baseOptions } = options;

  return {
    name: 'gwen:physics3d',

    // Expose for unit tests
    transformBvhReferences,

    async transform(code, id) {
      if (!/\.(ts|tsx|js|jsx)$/.test(id)) return;

      let s: MagicString | null = null;
      let layersModified = false;

      // ── Layer inlining (synchronous) ──────────────────────────────────────
      if (code.includes('defineLayers')) {
        const layerMap = extractLayerDefinitions(code);
        if (layerMap) {
          const declRe = /const\s+(\w+)\s*=\s*defineLayers\s*\([^)]*\)\s*;?/;
          const varMatch = code.match(declRe);
          if (varMatch) {
            const varName = varMatch[1];
            const declStart = varMatch.index!;
            const declEnd = declStart + varMatch[0].length;

            s = new MagicString(code);

            for (const [name, value] of layerMap) {
              const refRe = new RegExp(`\\b${varName}\\.${name}\\b`, 'g');
              let count = 0;
              for (const m of code.matchAll(refRe)) {
                s.overwrite(m.index!, m.index! + m[0].length, String(value));
                layersModified = true;
                count++;
              }
              if (count === 0) {
                this.warn(
                  `[gwen:physics3d] Layer "${name}" is defined but never referenced. Consider removing it.`,
                );
              }
            }

            if (layersModified) {
              // Remove the defineLayers declaration if the variable is no longer referenced
              // outside the declaration itself
              const transformed = s.toString();
              const beforeDecl = transformed.slice(0, declStart);
              const afterDecl = transformed.slice(declEnd);
              const varStillUsed = new RegExp(`\\b${varName}\\b`).test(beforeDecl + afterDecl);
              if (!varStillUsed) {
                s.remove(declStart, declEnd);
              }

              if (baseOptions.debug) {
                console.log(`[gwen:physics3d] Inlined ${layerMap.size} layer constants in ${id}`);
              }
            }
          }
        }
      }

      // ── BVH pre-baking (async, build mode only) ────────────────────────────
      const currentCode = s ? s.toString() : code;
      if (bvhPrebake && !id.includes('node_modules')) {
        const bvhResult = await transformBvhReferences(
          currentCode,
          id,
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          (this as any).emitFile?.bind(this),
        );
        if (bvhResult !== null) {
          // BVH transform happened on top of layer-inlined code; build a new MagicString
          // for the combined result (source map will cover the BVH transform only in this case,
          // but layer inlining map is still available from `s`).
          const combined = new MagicString(code);
          combined.overwrite(0, code.length, bvhResult);
          return {
            code: bvhResult,
            map: combined.generateMap({ hires: true, source: id, includeContent: true }),
          };
        }
      }

      if (!s || !layersModified) return undefined;

      return {
        code: s.toString(),
        map: s.generateMap({ hires: true, source: id, includeContent: true }),
      };
    },
  };
}

/**
 * @deprecated Use `physics3dVitePlugin({ bvhPrebake: true })` instead.
 */
export function createGwenPhysics3DPlugin(options: GwenPhysics3DPluginOptions = {}): Plugin & {
  /** @internal Exposed for unit tests. */
  transformBvhReferences: typeof transformBvhReferences;
} {
  return physics3dVitePlugin({ ...options, bvhPrebake: true });
}
