/**
 * String Pool — bidirectional string ↔ i32 ID mapping.
 *
 * In zero-allocation ECS architectures, components must have fixed, predictable size in binary memory (ArrayBuffer).
 * Since strings have variable length, the ECS stores only the i32 ID generated by this dictionary.
 * Individual components that reference strings use the ID, not the string itself.
 */
export class StringPool {
  private strToId = new Map<string, number>();
  private idToStr = new Map<number, string>();
  private nextId = 1;

  /**
   * Get or create a unique ID for a string.
   *
   * ⚠️ **WARNING**: Never store string IDs in closures, globals, or outside component data.
   * IDs are ONLY valid within their pool's lifecycle (scene or persistent).
   *
   * ❌ **BAD**:
   * ```ts
   * const cachedId = GlobalStringPoolManager.scene.intern('Name');
   * ```
   *
   * ✅ **GOOD**:
   * ```ts
   * const name = 'Name'; // Store the string, not the ID
   * // Let the schema serializer handle intern() automatically
   * ```
   *
   * @param str The string to intern
   * @returns A unique 32-bit signed integer ID for this string
   */
  public intern(str: string): number {
    let id = this.strToId.get(str);
    if (id === undefined) {
      id = this.nextId++;
      this.strToId.set(str, id);
      this.idToStr.set(id, str);
    }
    return id;
  }

  /**
   * Retrieve the string associated with an ID.
   *
   * @param id The string ID
   * @returns The string, or empty string if not found
   */
  public get(id: number): string {
    return this.idToStr.get(id) ?? '';
  }

  /**
   * Clear all interned strings. Useful for tests or scene transitions.
   */
  public clear(): void {
    this.strToId.clear();
    this.idToStr.clear();
    this.nextId = 1;
  }

  /** Backward-compatible alias used by older tests/helpers. */
  public reset(): void {
    this.clear();
  }

  /**
   * Get the number of strings currently in this pool.
   * Useful for debugging and monitoring memory usage.
   */
  public get size(): number {
    return this.strToId.size;
  }
}

/**
 * String Pool Manager — manages separate pools for scene and persistent strings.
 *
 * **Scene Pool**: Cleared on every scene transition (default for `Types.string`)
 * **Persistent Pool**: Never cleared, for cross-scene data (use `Types.persistentString`)
 *
 * **⚠️ Rule of Thumb**:
 * - Default: Use `Types.string` (scene-scoped)
 * - Only use `Types.persistentString` for:
 *   - Player names from save files
 *   - User preferences
 *   - Configuration loaded once at startup
 */
export class StringPoolManager {
  /** Scene-scoped pool — cleared on every scene transition */
  public readonly scene = new StringPool();

  /** Persistent pool — never cleared, survives scene transitions */
  public readonly persistent = new StringPool();

  /** Enable debug warnings for potential memory leaks */
  private readonly debug: boolean;

  /**
   * Create a new StringPoolManager.
   *
   * @param debug - Enable debug warnings (e.g., for persistent pool growth). Defaults to false.
   */
  public constructor(debug: boolean = false) {
    this.debug = debug;
  }

  /**
   * Clear the scene pool (called during scene transitions).
   * The persistent pool is NOT affected.
   */
  public clearScene(): void {
    this.scene.clear();
  }

  /**
   * Get debug statistics about both pools.
   * Useful for monitoring memory usage and detecting leaks.
   */
  public getDebugStats(): { scenePoolSize: number; persistentPoolSize: number } {
    const stats = {
      scenePoolSize: this.scene.size,
      persistentPoolSize: this.persistent.size,
    };

    // Debug warning for persistent pool growth
    if (this.debug && stats.persistentPoolSize > 1000) {
      console.warn(
        `[StringPoolManager] persistentPool has ${stats.persistentPoolSize} entries. ` +
          `This may indicate a memory leak if strings are incorrectly marked as persistent.`,
      );
    }

    return stats;
  }
}

/**
 * Global StringPoolManager instance.
 * Manages both scene-scoped and persistent string pools.
 * Debug mode is disabled by default (pass true if needed during development).
 */
export const GlobalStringPoolManager = new StringPoolManager(false);

/**
 * Global StringPool alias bound to the scene pool.
 */
export const GlobalStringPool = GlobalStringPoolManager.scene;
