// Contract for the compiled Engine exports.
// `light` is the shared surface. `physics2d` and `physics3d` add the extra lines.
// A rebuilt binary whose glue parameters or wasm types differ fails
// wasm-export-signature.test.ts.
//
// CI installs Rust with `toolchain: stable`. There is no rust-toolchain file
// to pin. Regenerate this golden file on each toolchain bump.

export const JS_ENTITY_ID = [
  "__destroy_into_raw()",
  "free()",
  "get generation()",
  "get index()",
] as const;

export const LIGHT_JS = [
  "__destroy_into_raw()",
  "add_component(index, generation, component_type_id, data)",
  "add_entity_transform(index, x, y, rotation, scale_x, scale_y)",
  "alloc_shared_buffer(byte_length)",
  "bulk_destroy(indices)",
  "bulk_spawn_with_transforms(positions, rotations)",
  "count_entities()",
  "create_entity()",
  "delete_entity(index, generation)",
  "delta_time()",
  "dirty_transform_count()",
  "frame_count()",
  "free()",
  "free_shared_buffer(ptr, byte_length)",
  "get_component_raw(index, generation, component_type_id)",
  "get_components_bulk(slots, gens, component_type_id, out_buf)",
  "get_entity_generation(index)",
  "get_entity_local_rotation(index)",
  "get_entity_local_x(index)",
  "get_entity_local_y(index)",
  "get_entity_world_rotation(index)",
  "get_entity_world_x(index)",
  "get_entity_world_y(index)",
  "get_query_result_capacity()",
  "get_query_result_ptr()",
  "has_component(index, generation, component_type_id)",
  "has_entity_parent(index)",
  "is_alive(index, generation)",
  "query_entities(component_type_ids)",
  "query_entities_to_buffer(component_type_ids)",
  "query_read_bulk(component_type_ids, read_type_id, out_slots, out_gens, out_buf)",
  "query_write_bulk(slots, gens, write_type_id, data)",
  "register_component_type()",
  "remove_component(index, generation, component_type_id)",
  "remove_entity_from_query(index)",
  "reset_frame()",
  "set_components_bulk(slots, gens, component_type_id, data)",
  "set_entity_local_position(index, x, y)",
  "set_entity_local_rotation(index, rotation)",
  "set_entity_local_scale(index, scale_x, scale_y)",
  "set_entity_parent(child_index, parent_index, keep_world_pos)",
  "should_sleep()",
  "sleep_time_ms()",
  "stats()",
  "sync_transforms_from_buffer(ptr, max_entities)",
  "sync_transforms_to_buffer(ptr, max_entities)",
  "sync_transforms_to_buffer_sparse(ptr)",
  "tick(delta_ms)",
  "total_time()",
  "translate_entity(index, dx, dy)",
  "update_entity_archetype(_index, _component_type_ids)",
  "update_transforms()",
] as const;

export const PHYSICS2D_JS_EXTRA = [
  "path_find_2d(from_x, from_y, to_x, to_y)",
  "path_get_result_ptr()",
  "physics2d_bulk_apply_impulse(slots, gens, rigidbody_type_id, impulse_data)",
  "physics2d_bulk_sync_from_rapier(transform_type_id, out_slots, out_gens, out_buf)",
  "physics2d_bulk_sync_to_rapier(slots, gens, transform_type_id, data)",
  "physics_add_ball_collider(handle, radius, restitution, friction, is_sensor, density, membership, filter, collider_id, offset_x, offset_y)",
  "physics_add_box_collider(handle, hw, hh, restitution, friction, is_sensor, density, membership, filter, collider_id, offset_x, offset_y, one_way)",
  "physics_add_rigid_body(slot, x, y, body_type, mass, gravity_scale, linear_damping, angular_damping, vx, vy, ccd_enabled, extra_solver_iters)",
  "physics_apply_impulse(slot, ix, iy)",
  "physics_bulk_step_kinematics(slots, vx, vy, dt)",
  "physics_consume_event_metrics()",
  "physics_get_collision_event_count()",
  "physics_get_collision_events_ptr()",
  "physics_get_linear_velocity(slot)",
  "physics_get_position(slot)",
  "physics_get_sensor_state(slot, collider_id)",
  "physics_init(grav_x, grav_y, _max_entities)",
  "physics_load_tilemap_chunk_body(chunk_id, pseudo_entity, x, y)",
  "physics_point_query(x, y, membership, filter)",
  "physics_query_radius(x, y, radius, membership, filter)",
  "physics_query_rect(x, y, hw, hh, membership, filter)",
  "physics_remove_rigid_body(slot)",
  "physics_set_event_coalescing(_enabled)",
  "physics_set_global_ccd_enabled(_enabled)",
  "physics_set_kinematic_position(slot, x, y, angle)",
  "physics_set_linear_damping(slot, damping)",
  "physics_set_linear_velocity(slot, vx, vy)",
  "physics_set_quality(preset)",
  "physics_step(delta)",
  "physics_unload_tilemap_chunk_body(chunk_id)",
  "physics_update_sensor_state(_slot, _collider_id, _active)",
] as const;

export const PHYSICS3D_JS_EXTRA = [
  "physics3d_add_ball_joint(entity_a, entity_b, ax, ay, az, bx, by, bz)",
  "physics3d_add_body(entity_index, x, y, z, kind, mass, linear_damping, angular_damping)",
  "physics3d_add_box_collider(entity_index, half_x, half_y, half_z, offset_x, offset_y, offset_z, is_sensor, friction, restitution, layer_bits, mask_bits, collider_id)",
  "physics3d_add_capsule_collider(entity_index, radius, half_height, offset_x, offset_y, offset_z, is_sensor, friction, restitution, layer_bits, mask_bits, collider_id)",
  "physics3d_add_character_controller(entity_index, step_height, slope_limit, skin_width, snap_to_ground, slide_on_steep_slopes, apply_impulses_to_dynamic)",
  "physics3d_add_compound_collider(entity_index, shape_data, layer_bits, mask_bits)",
  "physics3d_add_convex_collider(entity_index, vertices, offset_x, offset_y, offset_z, is_sensor, friction, restitution, density, layer_bits, mask_bits, collider_id)",
  "physics3d_add_fixed_joint(entity_a, entity_b, ax, ay, az, bx, by, bz)",
  "physics3d_add_force(entity_index, fx, fy, fz)",
  "physics3d_add_force_at_point(entity_index, fx, fy, fz, px, py, pz)",
  "physics3d_add_heightfield_collider(entity_index, heights_flat, rows, cols, scale_x, scale_y, scale_z, friction, restitution, layer_bits, mask_bits, collider_id)",
  "physics3d_add_mesh_collider(entity_index, vertices, indices, offset_x, offset_y, offset_z, is_sensor, friction, restitution, layer_bits, mask_bits, collider_id)",
  "physics3d_add_prismatic_joint(entity_a, entity_b, ax, ay, az, bx, by, bz, axis_x, axis_y, axis_z, use_limits, limit_min, limit_max)",
  "physics3d_add_revolute_joint(entity_a, entity_b, ax, ay, az, bx, by, bz, axis_x, axis_y, axis_z, use_limits, limit_min, limit_max)",
  "physics3d_add_sphere_collider(entity_index, radius, offset_x, offset_y, offset_z, is_sensor, friction, restitution, layer_bits, mask_bits, collider_id)",
  "physics3d_add_spring_joint(entity_a, entity_b, ax, ay, az, bx, by, bz, rest_length, stiffness, damping)",
  "physics3d_add_torque(entity_index, tx, ty, tz)",
  "physics3d_apply_angular_impulse(entity_index, ax, ay, az)",
  "physics3d_apply_impulse(entity_index, ix, iy, iz)",
  "physics3d_bulk_apply_impulse(slots, gens, rigidbody_type_id, impulse_data)",
  "physics3d_bulk_spawn_static_boxes(entity_indices, positions_flat, half_extents_flat, friction, restitution, layer_bits, mask_bits)",
  "physics3d_bulk_step_kinematic_rotations(slots, wx, wy, wz, dt)",
  "physics3d_bulk_step_kinematics(slots, vx, vy, vz, dt)",
  "physics3d_bulk_sync_from_rapier(transform_type_id, out_slots, out_gens, out_buf)",
  "physics3d_bulk_sync_to_rapier(slots, gens, transform_type_id, data)",
  "physics3d_cast_ray(ox, oy, oz, dx, dy, dz, max_dist, layers, mask, solid)",
  "physics3d_cast_shape(pos_x, pos_y, pos_z, rot_x, rot_y, rot_z, rot_w, dir_x, dir_y, dir_z, shape_type, p0, p1, p2, max_dist, layers, mask)",
  "physics3d_character_controller_move(entity_index, vx, vy, vz, dt)",
  "physics3d_consume_events()",
  "physics3d_find_path_3d(from_x, from_y, from_z, to_x, to_y, to_z)",
  "physics3d_get_angular_velocity(entity_index)",
  "physics3d_get_body_kind(entity_index)",
  "physics3d_get_body_state(entity_index)",
  "physics3d_get_cc_sab_ptr()",
  "physics3d_get_collision_event_count()",
  "physics3d_get_collision_events_ptr()",
  "physics3d_get_gravity_scale(entity_index)",
  "physics3d_get_linear_velocity(entity_index)",
  "physics3d_get_max_cc_entities()",
  "physics3d_get_path_buffer_ptr_3d()",
  "physics3d_get_sensor_state(entity_index, sensor_id)",
  "physics3d_has_body(entity_index)",
  "physics3d_init(gx, gy, gz, _max_entities)",
  "physics3d_init_navgrid_3d(ptr, width, height, depth, cell_size, origin_x, origin_y, origin_z)",
  "physics3d_is_body_sleeping(entity_index)",
  "physics3d_load_bvh_collider(entity_index, bvh_bytes, offset_x, offset_y, offset_z, is_sensor, friction, restitution, layer_bits, mask_bits, collider_id)",
  "physics3d_lock_rotations(entity_index, x, y, z)",
  "physics3d_lock_translations(entity_index, x, y, z)",
  "physics3d_overlap_shape(pos_x, pos_y, pos_z, rot_x, rot_y, rot_z, rot_w, shape_type, p0, p1, p2, layers, mask, out_ptr, max_results)",
  "physics3d_project_point(px, py, pz, layers, mask, solid)",
  "physics3d_rebuild_mesh_collider(entity_index, collider_id, vertices_flat, indices_flat, offset_x, offset_y, offset_z, is_sensor, friction, restitution, layer_bits, mask_bits)",
  "physics3d_remove_body(entity_index)",
  "physics3d_remove_character_controller(entity_index)",
  "physics3d_remove_collider(entity_index, collider_id)",
  "physics3d_remove_joint(id)",
  "physics3d_set_angular_velocity(entity_index, ax, ay, az)",
  "physics3d_set_body_kind(entity_index, kind)",
  "physics3d_set_body_sleeping(entity_index, sleeping)",
  "physics3d_set_body_solver_iterations(entity_index, iterations)",
  "physics3d_set_body_state(entity_index, px, py, pz, qx, qy, qz, qw, vx, vy, vz, ax, ay, az)",
  "physics3d_set_event_coalescing(enabled)",
  "physics3d_set_gravity_scale(entity_index, scale)",
  "physics3d_set_joint_enabled(id, enabled)",
  "physics3d_set_joint_motor_position(id, target, stiffness, damping)",
  "physics3d_set_joint_motor_velocity(id, velocity, max_force)",
  "physics3d_set_kinematic_position(entity_index, px, py, pz, qx, qy, qz, qw)",
  "physics3d_set_linear_velocity(entity_index, vx, vy, vz)",
  "physics3d_set_quality(preset)",
  "physics3d_step(delta)",
  "physics3d_update_heightfield_collider(entity_index, collider_id, heights_flat, rows, cols, scale_x, scale_y, scale_z, friction, restitution, layer_bits, mask_bits)",
  "physics3d_update_sensor_state(entity_index, sensor_id, is_active, count)",
  "physics3d_wake_all()",
] as const;

export const LIGHT_WASM = [
  "engine_add_component (i32,i32,i32,i32,i32,i32,i32)->()",
  "engine_add_entity_transform (i32,i32,f32,f32,f32,f32,f32)->()",
  "engine_alloc_shared_buffer (i32,i32)->(i32)",
  "engine_bulk_destroy (i32,i32,i32)->()",
  "engine_bulk_spawn_with_transforms (i32,i32,i32,i32,i32,i32)->()",
  "engine_count_entities (i32)->(i32)",
  "engine_create_entity (i32,i32)->()",
  "engine_delete_entity (i32,i32,i32)->(i32)",
  "engine_delta_time (i32)->(f32)",
  "engine_dirty_transform_count (i32)->(i32)",
  "engine_frame_count (i32)->(i64)",
  "engine_free_shared_buffer (i32,i32,i32)->()",
  "engine_get_component_raw (i32,i32,i32,i32,i32)->()",
  "engine_get_components_bulk (i32,i32,i32,i32,i32,i32,i32,i32,i32)->(i32)",
  "engine_get_entity_generation (i32,i32)->(i32)",
  "engine_get_entity_local_rotation (i32,i32)->(f32)",
  "engine_get_entity_local_x (i32,i32)->(f32)",
  "engine_get_entity_local_y (i32,i32)->(f32)",
  "engine_get_entity_world_rotation (i32,i32)->(f32)",
  "engine_get_entity_world_x (i32,i32)->(f32)",
  "engine_get_entity_world_y (i32,i32)->(f32)",
  "engine_get_query_result_capacity (i32)->(i32)",
  "engine_get_query_result_ptr (i32)->(i32)",
  "engine_has_component (i32,i32,i32,i32)->(i32)",
  "engine_has_entity_parent (i32,i32)->(i32)",
  "engine_is_alive (i32,i32,i32)->(i32)",
  "engine_new (i32,i32)->()",
  "engine_query_entities (i32,i32,i32,i32)->()",
  "engine_query_entities_to_buffer (i32,i32,i32,i32)->()",
  "engine_query_read_bulk (i32,i32,i32,i32,i32,i32,i32,i32,i32,i32,i32,i32,i32,i32)->()",
  "engine_query_write_bulk (i32,i32,i32,i32,i32,i32,i32,i32,i32)->()",
  "engine_register_component_type (i32)->(i32)",
  "engine_remove_component (i32,i32,i32,i32)->(i32)",
  "engine_remove_entity_from_query (i32,i32)->()",
  "engine_reset_frame (i32)->()",
  "engine_set_components_bulk (i32,i32,i32,i32,i32,i32,i32,i32,i32)->()",
  "engine_set_entity_local_position (i32,i32,f32,f32)->()",
  "engine_set_entity_local_rotation (i32,i32,f32)->()",
  "engine_set_entity_local_scale (i32,i32,f32,f32)->()",
  "engine_set_entity_parent (i32,i32,i32,i32,i32)->()",
  "engine_should_sleep (i32)->(i32)",
  "engine_sleep_time_ms (i32)->(f32)",
  "engine_stats (i32,i32)->()",
  "engine_sync_transforms_from_buffer (i32,i32,i32,i32)->()",
  "engine_sync_transforms_to_buffer (i32,i32,i32,i32)->()",
  "engine_sync_transforms_to_buffer_sparse (i32,i32)->(i32)",
  "engine_tick (i32,f32)->()",
  "engine_total_time (i32)->(f32)",
  "engine_translate_entity (i32,i32,f32,f32)->()",
  "engine_update_entity_archetype (i32,i32,i32,i32)->()",
  "engine_update_transforms (i32)->()",
  "jsentityid_generation (i32)->(i32)",
  "jsentityid_index (i32)->(i32)",
] as const;

export const PHYSICS2D_WASM_EXTRA = [
  "engine_path_find_2d (i32,f32,f32,f32,f32)->(i32)",
  "engine_path_get_result_ptr (i32)->(i32)",
  "engine_physics2d_bulk_apply_impulse (i32,i32,i32,i32,i32,i32,i32,i32)->()",
  "engine_physics2d_bulk_sync_from_rapier (i32,i32,i32,i32,i32,i32,i32,i32,i32,i32,i32,i32)->()",
  "engine_physics2d_bulk_sync_to_rapier (i32,i32,i32,i32,i32,i32,i32,i32)->()",
  "engine_physics_add_ball_collider (i32,i32,f32,f32,f32,i32,f32,i32,i32,f64,f64,f64)->()",
  "engine_physics_add_box_collider (i32,i32,f32,f32,f32,f32,i32,f32,i32,i32,f64,f64,f64,f64)->()",
  "engine_physics_add_rigid_body (i32,i32,f32,f32,i32,f32,f32,f32,f32,f32,f32,f64,f64)->(i32)",
  "engine_physics_apply_impulse (i32,i32,f32,f32)->()",
  "engine_physics_bulk_step_kinematics (i32,i32,i32,i32,i32,i32,i32,f32)->(i32)",
  "engine_physics_consume_event_metrics (i32,i32)->()",
  "engine_physics_get_collision_event_count (i32)->(i32)",
  "engine_physics_get_collision_events_ptr (i32)->(i32)",
  "engine_physics_get_linear_velocity (i32,i32,i32)->()",
  "engine_physics_get_position (i32,i32,i32)->()",
  "engine_physics_get_sensor_state (i32,i32,i32,i32)->()",
  "engine_physics_init (i32,f32,f32,i32)->()",
  "engine_physics_load_tilemap_chunk_body (i32,i32,i32,f32,f32)->(i32)",
  "engine_physics_point_query (i32,i32,f32,f32,i32,i32)->()",
  "engine_physics_query_radius (i32,i32,f32,f32,f32,i32,i32)->()",
  "engine_physics_query_rect (i32,i32,f32,f32,f32,f32,i32,i32)->()",
  "engine_physics_remove_rigid_body (i32,i32)->()",
  "engine_physics_set_event_coalescing (i32,i32)->()",
  "engine_physics_set_global_ccd_enabled (i32,i32)->()",
  "engine_physics_set_kinematic_position (i32,i32,f32,f32,f32)->(i32)",
  "engine_physics_set_linear_damping (i32,i32,f32)->()",
  "engine_physics_set_linear_velocity (i32,i32,f32,f32)->(i32)",
  "engine_physics_set_quality (i32,i32)->()",
  "engine_physics_step (i32,f32)->()",
  "engine_physics_unload_tilemap_chunk_body (i32,i32)->()",
  "engine_physics_update_sensor_state (i32,i32,i32,i32)->()",
] as const;

export const PHYSICS3D_WASM_EXTRA = [
  "engine_physics3d_add_ball_joint (i32,i32,i32,f32,f32,f32,f32,f32,f32)->(i32)",
  "engine_physics3d_add_body (i32,i32,f32,f32,f32,i32,f32,f32,f32)->(i32)",
  "engine_physics3d_add_box_collider (i32,i32,f32,f32,f32,f32,f32,f32,i32,f32,f32,i32,i32,i32)->(i32)",
  "engine_physics3d_add_capsule_collider (i32,i32,f32,f32,f32,f32,f32,i32,f32,f32,i32,i32,i32)->(i32)",
  "engine_physics3d_add_character_controller (i32,i32,f32,f32,f32,f32,i32,i32)->(i32)",
  "engine_physics3d_add_compound_collider (i32,i32,i32,i32,i32,i32)->(i32)",
  "engine_physics3d_add_convex_collider (i32,i32,i32,i32,f32,f32,f32,i32,f32,f32,f32,i32,i32,i32)->(i32)",
  "engine_physics3d_add_fixed_joint (i32,i32,i32,f32,f32,f32,f32,f32,f32)->(i32)",
  "engine_physics3d_add_force (i32,i32,f32,f32,f32)->(i32)",
  "engine_physics3d_add_force_at_point (i32,i32,f32,f32,f32,f32,f32,f32)->(i32)",
  "engine_physics3d_add_heightfield_collider (i32,i32,i32,i32,i32,i32,f32,f32,f32,f32,f32,i32,i32,i32)->(i32)",
  "engine_physics3d_add_mesh_collider (i32,i32,i32,i32,i32,i32,f32,f32,f32,i32,f32,f32,i32,i32,i32)->(i32)",
  "engine_physics3d_add_prismatic_joint (i32,i32,i32,f32,f32,f32,f32,f32,f32,f32,f32,f32,i32,f32,f32)->(i32)",
  "engine_physics3d_add_revolute_joint (i32,i32,i32,f32,f32,f32,f32,f32,f32,f32,f32,f32,i32,f32,f32)->(i32)",
  "engine_physics3d_add_sphere_collider (i32,i32,f32,f32,f32,f32,i32,f32,f32,i32,i32,i32)->(i32)",
  "engine_physics3d_add_spring_joint (i32,i32,i32,f32,f32,f32,f32,f32,f32,f32,f32,f32)->(i32)",
  "engine_physics3d_add_torque (i32,i32,f32,f32,f32)->(i32)",
  "engine_physics3d_apply_angular_impulse (i32,i32,f32,f32,f32)->(i32)",
  "engine_physics3d_apply_impulse (i32,i32,f32,f32,f32)->(i32)",
  "engine_physics3d_bulk_apply_impulse (i32,i32,i32,i32,i32,i32,i32,i32)->()",
  "engine_physics3d_bulk_spawn_static_boxes (i32,i32,i32,i32,i32,i32,i32,f32,f32,i32,i32)->(i32)",
  "engine_physics3d_bulk_step_kinematic_rotations (i32,i32,i32,i32,i32,i32,i32,i32,i32,f32)->(i32)",
  "engine_physics3d_bulk_step_kinematics (i32,i32,i32,i32,i32,i32,i32,i32,i32,f32)->(i32)",
  "engine_physics3d_bulk_sync_from_rapier (i32,i32,i32,i32,i32,i32,i32,i32,i32,i32,i32,i32)->()",
  "engine_physics3d_bulk_sync_to_rapier (i32,i32,i32,i32,i32,i32,i32,i32)->()",
  "engine_physics3d_cast_ray (i32,i32,f32,f32,f32,f32,f32,f32,f32,i32,i32,i32)->()",
  "engine_physics3d_cast_shape (i32,i32,f32,f32,f32,f32,f32,f32,f32,f32,f32,f32,i32,f32,f32,f32,f32,i32,i32)->()",
  "engine_physics3d_character_controller_move (i32,i32,f32,f32,f32,f32)->()",
  "engine_physics3d_consume_events (i32)->()",
  "engine_physics3d_find_path_3d (i32,f32,f32,f32,f32,f32,f32)->(i32)",
  "engine_physics3d_get_angular_velocity (i32,i32,i32)->()",
  "engine_physics3d_get_body_kind (i32,i32)->(i32)",
  "engine_physics3d_get_body_state (i32,i32,i32)->()",
  "engine_physics3d_get_cc_sab_ptr (i32)->(i32)",
  "engine_physics3d_get_collision_event_count (i32)->(i32)",
  "engine_physics3d_get_collision_events_ptr (i32)->(i32)",
  "engine_physics3d_get_gravity_scale (i32,i32)->(f32)",
  "engine_physics3d_get_linear_velocity (i32,i32,i32)->()",
  "engine_physics3d_get_max_cc_entities (i32)->(i32)",
  "engine_physics3d_get_path_buffer_ptr_3d (i32)->(i32)",
  "engine_physics3d_get_sensor_state (i32,i32,i32)->(i64)",
  "engine_physics3d_has_body (i32,i32)->(i32)",
  "engine_physics3d_init (i32,f32,f32,f32,i32)->()",
  "engine_physics3d_init_navgrid_3d (i32,i32,i32,i32,i32,f32,f32,f32,f32)->()",
  "engine_physics3d_is_body_sleeping (i32,i32)->(i32)",
  "engine_physics3d_load_bvh_collider (i32,i32,i32,i32,f32,f32,f32,i32,f32,f32,i32,i32,i32)->(i32)",
  "engine_physics3d_lock_rotations (i32,i32,i32,i32,i32)->(i32)",
  "engine_physics3d_lock_translations (i32,i32,i32,i32,i32)->(i32)",
  "engine_physics3d_overlap_shape (i32,f32,f32,f32,f32,f32,f32,f32,i32,f32,f32,f32,i32,i32,i32,i32)->(i32)",
  "engine_physics3d_project_point (i32,i32,f32,f32,f32,i32,i32,i32)->()",
  "engine_physics3d_rebuild_mesh_collider (i32,i32,i32,i32,i32,i32,i32,f32,f32,f32,i32,f32,f32,i32,i32)->(i32)",
  "engine_physics3d_remove_body (i32,i32)->(i32)",
  "engine_physics3d_remove_character_controller (i32,i32)->()",
  "engine_physics3d_remove_collider (i32,i32,i32)->(i32)",
  "engine_physics3d_remove_joint (i32,i32)->(i32)",
  "engine_physics3d_set_angular_velocity (i32,i32,f32,f32,f32)->(i32)",
  "engine_physics3d_set_body_kind (i32,i32,i32)->(i32)",
  "engine_physics3d_set_body_sleeping (i32,i32,i32)->(i32)",
  "engine_physics3d_set_body_solver_iterations (i32,i32,i32)->(i32)",
  "engine_physics3d_set_body_state (i32,i32,f32,f32,f32,f32,f32,f32,f32,f32,f32,f32,f32,f32,f32)->(i32)",
  "engine_physics3d_set_event_coalescing (i32,i32)->()",
  "engine_physics3d_set_gravity_scale (i32,i32,f32)->(i32)",
  "engine_physics3d_set_joint_enabled (i32,i32,i32)->(i32)",
  "engine_physics3d_set_joint_motor_position (i32,i32,f32,f32,f32)->(i32)",
  "engine_physics3d_set_joint_motor_velocity (i32,i32,f32,f32)->(i32)",
  "engine_physics3d_set_kinematic_position (i32,i32,f32,f32,f32,f32,f32,f32,f32)->(i32)",
  "engine_physics3d_set_linear_velocity (i32,i32,f32,f32,f32)->(i32)",
  "engine_physics3d_set_quality (i32,i32)->()",
  "engine_physics3d_step (i32,f32)->()",
  "engine_physics3d_update_heightfield_collider (i32,i32,i32,i32,i32,i32,i32,f32,f32,f32,f32,f32,i32,i32)->(i32)",
  "engine_physics3d_update_sensor_state (i32,i32,i32,i32,i32)->()",
  "engine_physics3d_wake_all (i32)->()",
] as const;
