import assert from 'node:assert/strict';
import test from 'node:test';
import { hasAttribution, missingBreakingFooter } from './commitlint-gwen.mjs';

const authored = ['Co', 'authored-by'].join('-');
const generated = ['Generated', 'by'].join('-');
const made = ['Made', 'with'].join('-');
const breaking = ['BREAKING CHANGE', ':'].join('');

test('rejects an attribution trailer', () => {
  assert.equal(hasAttribution(`ci: fine\n\n${authored}: A <a@example.com>\n`), true);
  assert.equal(hasAttribution(`ci: fine\n\n${generated}: tool\n`), true);
  assert.equal(hasAttribution(`ci: fine\n\n${made}: tool\n`), true);
  assert.equal(hasAttribution('ci: fine\n\nGenerated by a tool\n'), true);
  assert.equal(hasAttribution('ci: fine\n\nMade with a tool\n'), true);
});

test('accepts a commit with no attribution trailer', () => {
  assert.equal(hasAttribution('ci: add agent hygiene checks\n\nScanners only.\n'), false);
});

test('requires a breaking footer when the header has a bang', () => {
  assert.equal(missingBreakingFooter('ci!: change the contract', 'ci!: change the contract\n'), true);
  assert.equal(
    missingBreakingFooter('ci!: change the contract', `ci!: change the contract\n\n${breaking} the contract\n`),
    false,
  );
  assert.equal(missingBreakingFooter('ci: no bang', 'ci: no bang\n'), false);
});
