/**
 * commitlint rules for agent commits.
 * Reject attribution trailers, and require a BREAKING CHANGE: footer
 * when the header contains "!".
 */

const ATTRIBUTION = [
  /co-authored-by\s*:/i,
  /^\s*co-author\s*:/im,
  /generated-by\s*:/i,
  /made-with\s*:/i,
  /^\s*generated by\b/im,
  /^\s*made with\b/im,
];

/**
 * @param {string | null | undefined} text
 * @returns {boolean}
 */
export function hasAttribution(text) {
  const raw = text ?? '';
  return ATTRIBUTION.some((pattern) => pattern.test(raw));
}

/**
 * @param {string | null | undefined} header
 * @param {string | null | undefined} raw
 * @returns {boolean}
 */
export function missingBreakingFooter(header, raw) {
  if (!(header ?? '').includes('!')) return false;
  return !(raw ?? '').includes('BREAKING CHANGE:');
}

/**
 * @param {{ raw?: string, header?: string, body?: string | null, footer?: string | null }} parsed
 * @returns {string}
 */
function rawOf(parsed) {
  if (parsed.raw) return parsed.raw;
  return [parsed.header, parsed.body, parsed.footer].filter((part) => part != null && part !== '').join('\n');
}

const gwenNoAttribution = (parsed) => {
  if (!hasAttribution(rawOf(parsed))) return [true];
  return [false, 'attribution trailers are rejected'];
};

const gwenBreakingFooter = (parsed) => {
  const raw = rawOf(parsed);
  if (!missingBreakingFooter(parsed.header, raw)) return [true];
  return [false, 'a header with ! needs a BREAKING CHANGE: footer'];
};

const plugin = {
  rules: {
    'gwen-no-attribution': gwenNoAttribution,
    'gwen-breaking-footer': gwenBreakingFooter,
  },
};

export default plugin;
