import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import type { Plugin } from 'vite';
import type { AutoImport } from '@gwenjs/kit';
import type { GwenViteOptions } from '../types.js';

const AUTO_IMPORTS_VIRTUAL = 'virtual:gwen/auto-imports';
const RESOLVED_AUTO_IMPORTS = '\0' + AUTO_IMPORTS_VIRTUAL;

/**
 * Generates a virtual module for auto-imports collected from GWEN modules.
 *
 * The virtual module `virtual:gwen/auto-imports` re-exports every registered
 * composable so that game files can import from the virtual module directly,
 * or rely on unplugin-auto-import with the generated stub.
 *
 * @example vite.config.ts
 * ```ts
 * gwenAutoImportsPlugin({
 *   autoImports: [
 *     { name: 'usePhysics2D', from: '@gwenjs/physics2d' },
 *   ],
 * })
 * ```
 */
export function gwenAutoImportsPlugin(options: GwenViteOptions): Plugin {
  const entries = options.autoImports ?? [];
  let root = process.cwd();

  return {
    name: 'gwen:auto-imports',

    configResolved(config) {
      root = config.root;
    },

    buildStart() {
      if (options.dts !== false) {
        writeDts(root, options.gwenDir ?? '.gwen', entries);
      }
    },

    resolveId(id) {
      if (id === AUTO_IMPORTS_VIRTUAL) return RESOLVED_AUTO_IMPORTS;
    },

    load(id) {
      if (id !== RESOLVED_AUTO_IMPORTS) return;
      return generateAutoImportsModule(entries);
    },
  };
}

/**
 * Generates the virtual module source that re-exports all auto-imports.
 *
 * Entries are grouped by their `from` field so that multiple exports from
 * the same package are combined into a single `export { … } from '…'` line.
 * Aliased imports use the `name as alias` syntax.
 *
 * @param entries - The list of {@link AutoImport} entries to codegen.
 * @returns A string of ESM re-export statements, or a comment when empty.
 *
 * @example Empty
 * ```ts
 * generateAutoImportsModule([])
 * // => '// no auto-imports registered\n'
 * ```
 *
 * @example Grouped
 * ```ts
 * generateAutoImportsModule([
 *   { name: 'useEngine', from: '@gwenjs/core' },
 *   { name: 'defineSystem', from: '@gwenjs/core' },
 * ])
 * // => "export { useEngine, defineSystem } from '@gwenjs/core'\n"
 * ```
 */
export function generateAutoImportsModule(entries: AutoImport[]): string {
  if (entries.length === 0) return '// no auto-imports registered\n';

  // Group by source package
  const grouped = new Map<string, Array<{ name: string; as?: string }>>();
  for (const entry of entries) {
    const list = grouped.get(entry.from) ?? [];
    list.push({ name: entry.name, as: entry.as });
    grouped.set(entry.from, list);
  }

  const lines: string[] = [];
  for (const [from, names] of grouped) {
    const specifiers = names.map(({ name, as }) => (as ? `${name} as ${as}` : name)).join(', ');
    lines.push(`export { ${specifiers} } from '${from}'`);
  }

  return lines.join('\n') + '\n';
}

/**
 * Writes `.gwen/types/auto-imports.d.ts` with global type declarations
 * so TypeScript knows about auto-imported symbols without explicit imports.
 *
 * @param root - Project root directory (from Vite's `config.root`).
 * @param gwenDir - Relative path to the GWEN output directory.
 * @param entries - The auto-import entries to declare.
 */
function writeDts(root: string, gwenDir: string, entries: AutoImport[]): void {
  if (entries.length === 0) return;

  const dir = resolve(root, gwenDir, 'types');
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  const lines = [
    '// Generated by @gwenjs/vite — do not edit',
    '// Auto-imports type declarations',
    '',
    'export {}',
    '',
    'declare global {',
  ];

  for (const { name, as, from } of entries) {
    const localName = as ?? name;
    lines.push(`  const ${localName}: typeof import('${from}')['${name}']`);
  }

  lines.push('}', '');

  writeFileSync(resolve(dir, 'auto-imports.d.ts'), lines.join('\n'));
}
