import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import type { Plugin } from "vite";
import { createUnimport, type Unimport } from "unimport";
import type { AutoImport } from "@gwenjs/kit";
import type { GwenViteOptions } from "../types.js";

const AUTO_IMPORTS_VIRTUAL = "virtual:gwen/auto-imports";
const RESOLVED_AUTO_IMPORTS = "\0" + AUTO_IMPORTS_VIRTUAL;

/**
 * Provides auto-imports for all composables registered by GWEN modules.
 *
 * Two mechanisms:
 * 1. **Transform injection** — scans user files and injects `import { … } from '…'`
 *    for any registered composable used without an explicit import.
 * 2. **Virtual module** — `virtual:gwen/auto-imports` / `#gwen` re-exports everything
 *    for explicit barrel-style imports.
 * 3. **DTS** — writes `.gwen/types/auto-imports.d.ts` so TypeScript sees the globals.
 */
export function gwenAutoImportsPlugin(options: GwenViteOptions): Plugin {
  const entries = options.autoImports ?? [];
  let root = process.cwd();
  let ui: Unimport | null = null;

  function getUnimport(): Unimport {
    if (!ui) {
      ui = createUnimport({
        imports: entries.map((e) => ({
          name: e.name,
          as: e.as ?? e.name,
          from: e.from,
        })),
      });
    }
    return ui;
  }

  return {
    name: "gwen:auto-imports",

    configResolved(config) {
      root = config.root;
    },

    buildStart() {
      // Reset so getUnimport() picks up the fully-populated entries array.
      ui = null;
      if (options.dts !== false) {
        writeDts(root, options.gwenDir ?? ".gwen", entries);
      }
    },

    resolveId(id) {
      if (id === "#gwen" || id === AUTO_IMPORTS_VIRTUAL) return RESOLVED_AUTO_IMPORTS;
    },

    load(id) {
      if (id !== RESOLVED_AUTO_IMPORTS) return;
      return generateAutoImportsModule(entries);
    },

    async transform(code, id) {
      if (!id.match(/\.(ts|tsx|js|jsx)$/)) return;
      if (id.includes("/node_modules/")) return;
      if (id.startsWith("\0")) return;
      if (entries.length === 0) return;

      const result = await getUnimport().injectImports(code, id);
      if (!result.s?.hasChanged()) return;

      return {
        code: result.s.toString(),
        map: result.s.generateMap({ hires: true, source: id, includeContent: true }),
      };
    },
  };
}

/**
 * Generates the virtual module source that re-exports all auto-imports.
 */
export function generateAutoImportsModule(entries: AutoImport[]): string {
  if (entries.length === 0) return "// no auto-imports registered\n";

  const grouped = new Map<string, Array<{ name: string; as?: string }>>();
  for (const entry of entries) {
    const list = grouped.get(entry.from) ?? [];
    list.push({ name: entry.name, as: entry.as });
    grouped.set(entry.from, list);
  }

  const lines: string[] = [];
  for (const [from, names] of grouped) {
    const specifiers = names.map(({ name, as }) => (as ? `${name} as ${as}` : name)).join(", ");
    lines.push(`export { ${specifiers} } from '${from}'`);
  }

  return lines.join("\n") + "\n";
}

/**
 * Writes `.gwen/types/auto-imports.d.ts` with global type declarations.
 */
function writeDts(root: string, gwenDir: string, entries: AutoImport[]): void {
  if (entries.length === 0) return;

  const dir = resolve(root, gwenDir, "types");
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  const lines = [
    "// Generated by @gwenjs/vite — do not edit",
    "// Auto-imports type declarations",
    "",
    "export {}",
    "",
    "declare global {",
  ];

  for (const { name, as, from } of entries) {
    const localName = as ?? name;
    lines.push(`  const ${localName}: typeof import('${from}')['${name}']`);
  }

  lines.push("}", "");

  writeFileSync(resolve(dir, "auto-imports.d.ts"), lines.join("\n"));
}
