import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve, relative, join } from "node:path";
import type { Plugin } from "vite";
import type { VariableDeclarator } from "oxc-parser";
import { walk } from "oxc-walker";
import { parseSource, isCallTo } from "../oxc/index.js";
import type { GwenViteOptions } from "../types.js";

/**
 * Extract variable names bound to `defineHooks(...)` calls in the given source.
 * Uses OXC AST parsing to avoid false positives in comments or strings.
 *
 * @param code - TypeScript source code to scan.
 * @param filename - File path used by the parser for diagnostics.
 * @returns Array of variable names in declaration order.
 */
export function extractDefineHooksExports(code: string, filename = "hooks.ts"): string[] {
  const names: string[] = [];
  if (!code.includes("defineHooks")) return names;

  const parsed = parseSource(filename, code);
  if (!parsed) return names;

  walk(parsed.program, {
    enter(node) {
      if (node.type !== "VariableDeclarator") return;
      const { id, init } = node as VariableDeclarator;
      if (id.type !== "Identifier") return;
      if (!init || !isCallTo(init, "defineHooks")) return;
      names.push((id as { name: string }).name);
    },
  });

  return names;
}

/**
 * Generate `.d.ts` content that augments `GwenRuntimeHooks` with the given
 * `defineHooks` exports.
 *
 * Returns an empty string when `exportNames` is empty (nothing to generate).
 *
 * @param exportNames - Variable names returned by `extractDefineHooksExports`.
 * @param importPath - Relative import path from the `.d.ts` file to the hooks
 *   source file, without file extension (e.g. `'../../src/hooks'`).
 * @returns Complete `.d.ts` file content, or `''` when `exportNames` is empty.
 */
export function generateHooksDts(exportNames: string[], importPath: string): string {
  if (exportNames.length === 0) return "";

  const namedImports = exportNames.join(", ");
  const extendsClause = exportNames.map((n) => `InferHooks<typeof ${n}>`).join(", ");

  return [
    "// Auto-generated by @gwenjs/vite — do not edit",
    "import type { InferHooks } from '@gwenjs/core';",
    `import type { ${namedImports} } from '${importPath}';`,
    "",
    "declare module '@gwenjs/schema' {",
    `  interface GwenRuntimeHooks extends ${extendsClause} {}`,
    "}",
    "",
  ].join("\n");
}

/**
 * Options for the `gwen:hooks` sub-plugin.
 */
export interface HooksPluginOptions {
  /**
   * Path to the hooks file, relative to the project root.
   * @default 'src/hooks.ts'
   */
  file?: string;
}

/**
 * Vite sub-plugin that auto-generates `.gwen/types/hooks.d.ts`.
 *
 * Scans the configured hooks file for `const X = defineHooks(...)` declarations
 * and writes a `declare module '@gwenjs/schema'` augmentation so users never
 * have to write the boilerplate by hand.
 *
 * Runs at `buildStart` and re-runs on `handleHotUpdate` when the hooks file
 * changes. Silently does nothing when the hooks file does not exist or contains
 * no `defineHooks` calls.
 */
export function gwenHooksPlugin(options: GwenViteOptions): Plugin {
  const hooksFile = options.hooks?.file ?? "src/hooks.ts";
  const gwenDir = options.gwenDir ?? ".gwen";
  let root = process.cwd();

  function regenerate(): void {
    const hooksAbsPath = resolve(root, hooksFile);
    if (!existsSync(hooksAbsPath)) return;

    const code = readFileSync(hooksAbsPath, "utf-8");
    const exportNames = extractDefineHooksExports(code, hooksAbsPath);

    const typesDir = resolve(root, gwenDir, "types");
    const dtsDest = join(typesDir, "hooks.d.ts");

    // importPath: relative from typesDir to hooksAbsPath, without .ts extension
    const importPath = relative(typesDir, hooksAbsPath).replace(/\.ts$/, "").replace(/\\/g, "/");

    const content = generateHooksDts(exportNames, importPath);
    if (!content) return;

    mkdirSync(typesDir, { recursive: true });

    const existing = existsSync(dtsDest) ? readFileSync(dtsDest, "utf-8") : "";
    if (existing !== content) writeFileSync(dtsDest, content, "utf-8");
  }

  return {
    name: "gwen:hooks",

    configResolved(config) {
      root = config.root;
    },

    buildStart() {
      regenerate();
    },

    handleHotUpdate({ file }: { file: string }) {
      if (file !== resolve(root, hooksFile)) return;
      regenerate();
    },
  };
}
