import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from "node:fs";
import { resolve, relative, join, sep } from "node:path";
import type { Plugin } from "vite";
import type { VariableDeclarator } from "oxc-parser";
import { walk } from "oxc-walker";
import { parseSource, isCallTo } from "../oxc/index.js";
import type { GwenViteOptions } from "../types.js";

/**
 * Extract variable names bound to `defineHooks(...)` calls in the given source.
 * Uses OXC AST parsing to avoid false positives in comments or strings.
 *
 * @param code - TypeScript source code to scan.
 * @param filename - File path used by the parser for diagnostics.
 * @returns Array of variable names in declaration order.
 */
export function extractDefineHooksExports(code: string, filename = "hooks.ts"): string[] {
  const names: string[] = [];
  if (!code.includes("defineHooks")) return names;

  const parsed = parseSource(filename, code);
  if (!parsed) return names;

  walk(parsed.program, {
    enter(node) {
      if (node.type !== "VariableDeclarator") return;
      const { id, init } = node as VariableDeclarator;
      if (id.type !== "Identifier") return;
      if (!init || !isCallTo(init, "defineHooks")) return;
      names.push((id as { name: string }).name);
    },
  });

  return names;
}

/**
 * A single hooks source file with its resolved export names and import path.
 */
export interface HooksSource {
  /** Variable names bound to `defineHooks(...)` in this file. */
  exportNames: string[];
  /**
   * Relative import path from the generated `.d.ts` to this source file,
   * without file extension (e.g. `'../../src/hooks'`).
   */
  importPath: string;
}

/**
 * Generate `.d.ts` content that augments `GwenRuntimeHooks` with all
 * `defineHooks` exports from one or more source files.
 *
 * Returns an empty string when no source file contributes any exports.
 *
 * @param sources - Array of `{ exportNames, importPath }` entries, one per
 *   hooks source file. Entries with empty `exportNames` are ignored.
 * @returns Complete `.d.ts` file content, or `''` when there is nothing to emit.
 */
export function generateHooksDts(sources: HooksSource[]): string {
  const active = sources.filter((s) => s.exportNames.length > 0);
  if (active.length === 0) return "";

  const allNames = active.flatMap((s) => s.exportNames);
  const importLines = active.map(
    (s) => `import type { ${s.exportNames.join(", ")} } from '${s.importPath}';`,
  );
  const extendsClause = allNames.map((n) => `InferHooks<typeof ${n}>`).join(", ");

  return [
    "// Auto-generated by @gwenjs/vite — do not edit",
    "import type { InferHooks } from '@gwenjs/core';",
    ...importLines,
    "",
    "declare module '@gwenjs/schema' {",
    `  interface GwenRuntimeHooks extends ${extendsClause} {}`,
    "}",
    "",
  ].join("\n");
}

/**
 * Options for the `gwen:hooks` sub-plugin.
 */
export interface HooksPluginOptions {
  /**
   * Path to a single hooks file, relative to the project root.
   * Processed in addition to `dir` when both exist.
   * @default 'src/hooks.ts'
   */
  file?: string;
  /**
   * Directory of hooks files to scan (all `*.ts` files), relative to the
   * project root. Processed in addition to `file` when both exist.
   * @default 'src/hooks'
   */
  dir?: string;
}

/**
 * Vite sub-plugin that auto-generates `.gwen/types/hooks.d.ts`.
 *
 * Scans `src/hooks.ts` (single file) and/or every `*.ts` file inside
 * `src/hooks/` (directory) for `const X = defineHooks(...)` declarations,
 * then writes a single `declare module '@gwenjs/schema'` augmentation so
 * users never have to write the boilerplate by hand.
 *
 * Runs at `buildStart` and re-runs on `handleHotUpdate` whenever the single
 * file or any file inside the directory changes. Silently does nothing when
 * neither source exists or no `defineHooks` calls are found.
 */
export function gwenHooksPlugin(options: GwenViteOptions): Plugin {
  const hooksFile = options.hooks?.file ?? "src/hooks.ts";
  const hooksDir = options.hooks?.dir ?? "src/hooks";
  const gwenDir = options.gwenDir ?? ".gwen";
  let root = process.cwd();

  function buildSource(absPath: string, typesDir: string): HooksSource | null {
    if (!existsSync(absPath)) return null;
    const exportNames = extractDefineHooksExports(readFileSync(absPath, "utf-8"), absPath);
    if (exportNames.length === 0) return null;
    const importPath = relative(typesDir, absPath).replace(/\.ts$/, "").replace(/\\/g, "/");
    return { exportNames, importPath };
  }

  function regenerate(): void {
    const typesDir = resolve(root, gwenDir, "types");
    const sources: HooksSource[] = [];

    const fileSource = buildSource(resolve(root, hooksFile), typesDir);
    if (fileSource) sources.push(fileSource);

    const dirAbsPath = resolve(root, hooksDir);
    if (existsSync(dirAbsPath)) {
      for (const name of readdirSync(dirAbsPath).sort()) {
        if (!name.endsWith(".ts")) continue;
        const s = buildSource(join(dirAbsPath, name), typesDir);
        if (s) sources.push(s);
      }
    }

    const content = generateHooksDts(sources);
    if (!content) return;

    const dtsDest = join(typesDir, "hooks.d.ts");
    mkdirSync(typesDir, { recursive: true });
    const existing = existsSync(dtsDest) ? readFileSync(dtsDest, "utf-8") : "";
    if (existing !== content) writeFileSync(dtsDest, content, "utf-8");
  }

  return {
    name: "gwen:hooks",

    configResolved(config) {
      root = config.root;
    },

    buildStart() {
      regenerate();
    },

    handleHotUpdate({ file }: { file: string }) {
      const dirAbsPath = resolve(root, hooksDir);
      const isFile = file === resolve(root, hooksFile);
      const isInDir = file.startsWith(dirAbsPath + sep) && file.endsWith(".ts");
      if (!isFile && !isInDir) return;
      regenerate();
    },
  };
}
