import type { VariableDeclarator } from "oxc-parser";
import { walk } from "oxc-walker";
import { parseSource, isCallTo } from "../oxc/index.js";

/**
 * Extract variable names bound to `defineHooks(...)` calls in the given source.
 * Uses OXC AST parsing to avoid false positives in comments or strings.
 *
 * @param code - TypeScript source code to scan.
 * @param filename - File path used by the parser for diagnostics.
 * @returns Array of variable names in declaration order.
 */
export function extractDefineHooksExports(code: string, filename = "hooks.ts"): string[] {
  const names: string[] = [];
  if (!code.includes("defineHooks")) return names;

  const parsed = parseSource(filename, code);
  if (!parsed) return names;

  walk(parsed.program, {
    enter(node) {
      if (node.type !== "VariableDeclarator") return;
      const { id, init } = node as VariableDeclarator;
      if (id.type !== "Identifier") return;
      if (!init || !isCallTo(init, "defineHooks")) return;
      names.push((id as { name: string }).name);
    },
  });

  return names;
}

/**
 * Generate `.d.ts` content that augments `GwenRuntimeHooks` with the given
 * `defineHooks` exports.
 *
 * Returns an empty string when `exportNames` is empty (nothing to generate).
 *
 * @param exportNames - Variable names returned by `extractDefineHooksExports`.
 * @param importPath - Relative import path from the `.d.ts` file to the hooks
 *   source file, without file extension (e.g. `'../../src/hooks'`).
 * @returns Complete `.d.ts` file content, or `''` when `exportNames` is empty.
 */
export function generateHooksDts(exportNames: string[], importPath: string): string {
  if (exportNames.length === 0) return "";

  const namedImports = exportNames.join(", ");
  const extendsClause = exportNames.map((n) => `InferHooks<typeof ${n}>`).join(", ");

  return [
    "// Auto-generated by @gwenjs/vite — do not edit",
    "import type { InferHooks } from '@gwenjs/core';",
    `import type { ${namedImports} } from '${importPath}';`,
    "",
    "declare module '@gwenjs/schema' {",
    `  interface GwenRuntimeHooks extends ${extendsClause} {}`,
    "}",
    "",
  ].join("\n");
}
