import { describe, it, expect, beforeEach, afterEach } from "vitest";
import fs from "node:fs";
import os from "node:os";
import * as path from "node:path";
import {
  extractDefineHooksExports,
  generateHooksDts,
  gwenHooksPlugin,
  type HooksSource,
} from "../../src/plugins/hooks.js";

describe("extractDefineHooksExports()", () => {
  it("returns empty array when no defineHooks call", () => {
    expect(extractDefineHooksExports("const x = 1;")).toEqual([]);
  });

  it("returns empty array fast-path when 'defineHooks' not in source text", () => {
    expect(extractDefineHooksExports("export const x = defineEvents({})")).toEqual([]);
  });

  it("extracts a single const binding", () => {
    const code = `const GameHooks = defineHooks({ 'enemy:died': (_id: bigint): void => undefined })`;
    expect(extractDefineHooksExports(code)).toEqual(["GameHooks"]);
  });

  it("extracts export const binding", () => {
    const code = `export const GameHooks = defineHooks({ 'foo:bar': (): void => undefined })`;
    expect(extractDefineHooksExports(code)).toEqual(["GameHooks"]);
  });

  it("extracts multiple bindings in declaration order", () => {
    const code = `
      const GameHooks = defineHooks({ 'enemy:died': () => undefined });
      const UIHooks = defineHooks({ 'ui:open': () => undefined });
    `;
    expect(extractDefineHooksExports(code)).toEqual(["GameHooks", "UIHooks"]);
  });

  it("ignores variables not bound to defineHooks", () => {
    const code = `
      const GameHooks = defineHooks({ 'foo:bar': () => undefined });
      const other = somethingElse();
    `;
    expect(extractDefineHooksExports(code)).toEqual(["GameHooks"]);
  });

  it("ignores defineHooks in a comment", () => {
    const code = `// const Foo = defineHooks({})`;
    expect(extractDefineHooksExports(code)).toEqual([]);
  });
});

function src(exportNames: string[], importPath: string): HooksSource {
  return { exportNames, importPath };
}

describe("generateHooksDts()", () => {
  it("returns empty string when all sources have no exports", () => {
    expect(generateHooksDts([])).toBe("");
    expect(generateHooksDts([src([], "../../src/hooks")])).toBe("");
  });

  it("includes the do-not-edit banner", () => {
    const dts = generateHooksDts([src(["GameHooks"], "../../src/hooks")]);
    expect(dts).toContain("Auto-generated by @gwenjs/vite");
  });

  it("imports InferHooks from @gwenjs/core", () => {
    const dts = generateHooksDts([src(["GameHooks"], "../../src/hooks")]);
    expect(dts).toContain("import type { InferHooks } from '@gwenjs/core'");
  });

  it("imports all export names from the given importPath", () => {
    const dts = generateHooksDts([src(["GameHooks", "UIHooks"], "../../src/hooks")]);
    expect(dts).toContain("import type { GameHooks, UIHooks } from '../../src/hooks'");
  });

  it("augments GwenRuntimeHooks with InferHooks for a single export", () => {
    const dts = generateHooksDts([src(["GameHooks"], "../../src/hooks")]);
    expect(dts).toContain("declare module '@gwenjs/schema'");
    expect(dts).toContain("interface GwenRuntimeHooks extends InferHooks<typeof GameHooks>");
  });

  it("extends multiple InferHooks for multiple exports in one source", () => {
    const dts = generateHooksDts([src(["GameHooks", "UIHooks"], "../../src/hooks")]);
    expect(dts).toContain("InferHooks<typeof GameHooks>, InferHooks<typeof UIHooks>");
  });

  it("merges exports from multiple source files into one augmentation block", () => {
    const dts = generateHooksDts([
      src(["GameHooks"], "../../src/hooks"),
      src(["UIHooks"], "../../src/hooks/ui"),
    ]);
    expect(dts).toContain("import type { GameHooks } from '../../src/hooks'");
    expect(dts).toContain("import type { UIHooks } from '../../src/hooks/ui'");
    expect(dts).toContain("InferHooks<typeof GameHooks>, InferHooks<typeof UIHooks>");
    expect((dts.match(/declare module/g) ?? []).length).toBe(1);
  });

  it("skips sources with empty exportNames when merging", () => {
    const dts = generateHooksDts([
      src([], "../../src/hooks"),
      src(["UIHooks"], "../../src/hooks/ui"),
    ]);
    expect(dts).not.toContain("from '../../src/hooks'");
    expect(dts).toContain("UIHooks");
  });

  it("output ends with a newline", () => {
    const dts = generateHooksDts([src(["GameHooks"], "../../src/hooks")]);
    expect(dts.endsWith("\n")).toBe(true);
  });
});

// ── gwenHooksPlugin ───────────────────────────────────────────────────────────

function makeTmp(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), "gwen-hooks-plugin-test-"));
}

describe("gwenHooksPlugin — buildStart", () => {
  let tmp: string;

  beforeEach(() => {
    tmp = makeTmp();
    // Simulate project root structure
    fs.mkdirSync(path.join(tmp, "src"), { recursive: true });
  });

  afterEach(() => {
    fs.rmSync(tmp, { recursive: true });
  });

  it("writes hooks.d.ts when src/hooks.ts contains defineHooks exports", () => {
    fs.writeFileSync(
      path.join(tmp, "src", "hooks.ts"),
      `export const GameHooks = defineHooks({ 'enemy:died': (_id: bigint): void => undefined })`,
    );

    const plugin = gwenHooksPlugin({});
    // Simulate configResolved
    (plugin.configResolved as Function)({ root: tmp });
    // Run buildStart
    (plugin.buildStart as Function).call({});

    const dtsPath = path.join(tmp, ".gwen", "types", "hooks.d.ts");
    expect(fs.existsSync(dtsPath)).toBe(true);

    const content = fs.readFileSync(dtsPath, "utf-8");
    expect(content).toContain("Auto-generated by @gwenjs/vite");
    expect(content).toContain("InferHooks<typeof GameHooks>");
    expect(content).toContain("from '../../src/hooks'");
  });

  it("does nothing when src/hooks.ts does not exist", () => {
    const plugin = gwenHooksPlugin({});
    (plugin.configResolved as Function)({ root: tmp });
    expect(() => (plugin.buildStart as Function).call({})).not.toThrow();

    const dtsPath = path.join(tmp, ".gwen", "types", "hooks.d.ts");
    expect(fs.existsSync(dtsPath)).toBe(false);
  });

  it("does nothing when src/hooks.ts has no defineHooks calls", () => {
    fs.writeFileSync(path.join(tmp, "src", "hooks.ts"), "export const x = 1;\n");

    const plugin = gwenHooksPlugin({});
    (plugin.configResolved as Function)({ root: tmp });
    (plugin.buildStart as Function).call({});

    const dtsPath = path.join(tmp, ".gwen", "types", "hooks.d.ts");
    expect(fs.existsSync(dtsPath)).toBe(false);
  });

  it("respects custom hooks.file option", () => {
    fs.mkdirSync(path.join(tmp, "src", "game"), { recursive: true });
    fs.writeFileSync(
      path.join(tmp, "src", "game", "hooks.ts"),
      `export const GameHooks = defineHooks({ 'foo:bar': (): void => undefined })`,
    );

    const plugin = gwenHooksPlugin({ hooks: { file: "src/game/hooks.ts" } });
    (plugin.configResolved as Function)({ root: tmp });
    (plugin.buildStart as Function).call({});

    const dtsPath = path.join(tmp, ".gwen", "types", "hooks.d.ts");
    expect(fs.existsSync(dtsPath)).toBe(true);
    const content = fs.readFileSync(dtsPath, "utf-8");
    expect(content).toContain("from '../../src/game/hooks'");
  });

  it("does not rewrite the file when content is unchanged", () => {
    fs.writeFileSync(
      path.join(tmp, "src", "hooks.ts"),
      `export const GameHooks = defineHooks({ 'foo:bar': (): void => undefined })`,
    );

    const plugin = gwenHooksPlugin({});
    (plugin.configResolved as Function)({ root: tmp });
    (plugin.buildStart as Function).call({});

    const dtsPath = path.join(tmp, ".gwen", "types", "hooks.d.ts");
    const mtime1 = fs.statSync(dtsPath).mtimeMs;

    // Run again — content identical → no write
    (plugin.buildStart as Function).call({});
    const mtime2 = fs.statSync(dtsPath).mtimeMs;

    expect(mtime2).toBe(mtime1);
  });
});

describe("gwenHooksPlugin — handleHotUpdate", () => {
  let tmp: string;

  beforeEach(() => {
    tmp = makeTmp();
    fs.mkdirSync(path.join(tmp, "src"), { recursive: true });
  });

  afterEach(() => {
    fs.rmSync(tmp, { recursive: true });
  });

  it("regenerates hooks.d.ts when the hooks file is updated", () => {
    fs.writeFileSync(
      path.join(tmp, "src", "hooks.ts"),
      `export const GameHooks = defineHooks({ 'enemy:died': (_id: bigint): void => undefined })`,
    );

    const plugin = gwenHooksPlugin({});
    (plugin.configResolved as Function)({ root: tmp });
    (plugin.buildStart as Function).call({});

    // Simulate adding a second hook export
    fs.writeFileSync(
      path.join(tmp, "src", "hooks.ts"),
      [
        `export const GameHooks = defineHooks({ 'enemy:died': (_id: bigint): void => undefined })`,
        `export const UIHooks = defineHooks({ 'ui:open': (): void => undefined })`,
      ].join("\n"),
    );

    (plugin.handleHotUpdate as Function)({ file: path.join(tmp, "src", "hooks.ts") });

    const content = fs.readFileSync(path.join(tmp, ".gwen", "types", "hooks.d.ts"), "utf-8");
    expect(content).toContain("InferHooks<typeof GameHooks>, InferHooks<typeof UIHooks>");
  });

  it("ignores hot updates for unrelated files", () => {
    fs.writeFileSync(
      path.join(tmp, "src", "hooks.ts"),
      `export const GameHooks = defineHooks({ 'foo:bar': (): void => undefined })`,
    );

    const plugin = gwenHooksPlugin({});
    (plugin.configResolved as Function)({ root: tmp });
    (plugin.buildStart as Function).call({});

    const dtsPath = path.join(tmp, ".gwen", "types", "hooks.d.ts");
    const mtime1 = fs.statSync(dtsPath).mtimeMs;

    // Trigger HMR for an unrelated file
    (plugin.handleHotUpdate as Function)({ file: path.join(tmp, "src", "other.ts") });

    const mtime2 = fs.statSync(dtsPath).mtimeMs;
    expect(mtime2).toBe(mtime1);
  });
});

// ── Directory scanning ────────────────────────────────────────────────────────

describe("gwenHooksPlugin — src/hooks/ directory scanning", () => {
  let tmp: string;

  beforeEach(() => {
    tmp = makeTmp();
    fs.mkdirSync(path.join(tmp, "src", "hooks"), { recursive: true });
  });

  afterEach(() => {
    fs.rmSync(tmp, { recursive: true });
  });

  it("merges exports from multiple files in src/hooks/ into one .d.ts", () => {
    fs.writeFileSync(
      path.join(tmp, "src", "hooks", "game.ts"),
      `export const GameHooks = defineHooks({ 'enemy:died': (_id: bigint): void => undefined })`,
    );
    fs.writeFileSync(
      path.join(tmp, "src", "hooks", "ui.ts"),
      `export const UIHooks = defineHooks({ 'ui:open': (): void => undefined })`,
    );

    const plugin = gwenHooksPlugin({});
    (plugin.configResolved as Function)({ root: tmp });
    (plugin.buildStart as Function).call({});

    const content = fs.readFileSync(path.join(tmp, ".gwen", "types", "hooks.d.ts"), "utf-8");
    expect(content).toContain("from '../../src/hooks/game'");
    expect(content).toContain("from '../../src/hooks/ui'");
    expect(content).toContain("InferHooks<typeof GameHooks>, InferHooks<typeof UIHooks>");
    expect((content.match(/declare module/g) ?? []).length).toBe(1);
  });

  it("processes both src/hooks.ts and src/hooks/ directory when both exist", () => {
    fs.mkdirSync(path.join(tmp, "src"), { recursive: true });
    fs.writeFileSync(
      path.join(tmp, "src", "hooks.ts"),
      `export const GameHooks = defineHooks({ 'enemy:died': (): void => undefined })`,
    );
    fs.writeFileSync(
      path.join(tmp, "src", "hooks", "ui.ts"),
      `export const UIHooks = defineHooks({ 'ui:open': (): void => undefined })`,
    );

    const plugin = gwenHooksPlugin({});
    (plugin.configResolved as Function)({ root: tmp });
    (plugin.buildStart as Function).call({});

    const content = fs.readFileSync(path.join(tmp, ".gwen", "types", "hooks.d.ts"), "utf-8");
    expect(content).toContain("from '../../src/hooks'");
    expect(content).toContain("from '../../src/hooks/ui'");
    expect(content).toContain("InferHooks<typeof GameHooks>");
    expect(content).toContain("InferHooks<typeof UIHooks>");
  });

  it("ignores non-.ts files in src/hooks/ directory", () => {
    fs.writeFileSync(
      path.join(tmp, "src", "hooks", "game.ts"),
      `export const GameHooks = defineHooks({ 'foo:bar': (): void => undefined })`,
    );
    fs.writeFileSync(path.join(tmp, "src", "hooks", "README.md"), "# Hooks");

    const plugin = gwenHooksPlugin({});
    (plugin.configResolved as Function)({ root: tmp });
    (plugin.buildStart as Function).call({});

    const content = fs.readFileSync(path.join(tmp, ".gwen", "types", "hooks.d.ts"), "utf-8");
    expect(content).not.toContain("README");
    expect(content).toContain("GameHooks");
  });

  it("regenerates when a file inside src/hooks/ changes via HMR", () => {
    fs.writeFileSync(
      path.join(tmp, "src", "hooks", "game.ts"),
      `export const GameHooks = defineHooks({ 'enemy:died': (): void => undefined })`,
    );

    const plugin = gwenHooksPlugin({});
    (plugin.configResolved as Function)({ root: tmp });
    (plugin.buildStart as Function).call({});

    // Add a second hook file
    fs.writeFileSync(
      path.join(tmp, "src", "hooks", "ui.ts"),
      `export const UIHooks = defineHooks({ 'ui:open': (): void => undefined })`,
    );

    (plugin.handleHotUpdate as Function)({ file: path.join(tmp, "src", "hooks", "ui.ts") });

    const content = fs.readFileSync(path.join(tmp, ".gwen", "types", "hooks.d.ts"), "utf-8");
    expect(content).toContain("UIHooks");
  });

  it("ignores HMR for files outside src/hooks/ that happen to end in .ts", () => {
    fs.writeFileSync(
      path.join(tmp, "src", "hooks", "game.ts"),
      `export const GameHooks = defineHooks({ 'foo:bar': (): void => undefined })`,
    );

    const plugin = gwenHooksPlugin({});
    (plugin.configResolved as Function)({ root: tmp });
    (plugin.buildStart as Function).call({});

    const dtsPath = path.join(tmp, ".gwen", "types", "hooks.d.ts");
    const mtime1 = fs.statSync(dtsPath).mtimeMs;

    (plugin.handleHotUpdate as Function)({ file: path.join(tmp, "src", "systems", "game.ts") });

    expect(fs.statSync(dtsPath).mtimeMs).toBe(mtime1);
  });

  it("respects custom hooks.dir option", () => {
    fs.mkdirSync(path.join(tmp, "src", "events"), { recursive: true });
    fs.writeFileSync(
      path.join(tmp, "src", "events", "game.ts"),
      `export const GameHooks = defineHooks({ 'foo:bar': (): void => undefined })`,
    );

    const plugin = gwenHooksPlugin({ hooks: { dir: "src/events" } });
    (plugin.configResolved as Function)({ root: tmp });
    (plugin.buildStart as Function).call({});

    const content = fs.readFileSync(path.join(tmp, ".gwen", "types", "hooks.d.ts"), "utf-8");
    expect(content).toContain("from '../../src/events/game'");
  });
});
