import { describe, it, expect } from "vitest";
import { extractDefineHooksExports, generateHooksDts } from "../../src/plugins/hooks.js";

describe("extractDefineHooksExports()", () => {
  it("returns empty array when no defineHooks call", () => {
    expect(extractDefineHooksExports("const x = 1;")).toEqual([]);
  });

  it("returns empty array fast-path when 'defineHooks' not in source text", () => {
    expect(extractDefineHooksExports("export const x = defineEvents({})")).toEqual([]);
  });

  it("extracts a single const binding", () => {
    const code = `const GameHooks = defineHooks({ 'enemy:died': (_id: bigint): void => undefined })`;
    expect(extractDefineHooksExports(code)).toEqual(["GameHooks"]);
  });

  it("extracts export const binding", () => {
    const code = `export const GameHooks = defineHooks({ 'foo:bar': (): void => undefined })`;
    expect(extractDefineHooksExports(code)).toEqual(["GameHooks"]);
  });

  it("extracts multiple bindings in declaration order", () => {
    const code = `
      const GameHooks = defineHooks({ 'enemy:died': () => undefined });
      const UIHooks = defineHooks({ 'ui:open': () => undefined });
    `;
    expect(extractDefineHooksExports(code)).toEqual(["GameHooks", "UIHooks"]);
  });

  it("ignores variables not bound to defineHooks", () => {
    const code = `
      const GameHooks = defineHooks({ 'foo:bar': () => undefined });
      const other = somethingElse();
    `;
    expect(extractDefineHooksExports(code)).toEqual(["GameHooks"]);
  });

  it("ignores defineHooks in a comment", () => {
    const code = `// const Foo = defineHooks({})`;
    expect(extractDefineHooksExports(code)).toEqual([]);
  });
});

describe("generateHooksDts()", () => {
  it("returns empty string when exportNames is empty", () => {
    expect(generateHooksDts([], "../../src/hooks")).toBe("");
  });

  it("includes the do-not-edit banner", () => {
    const dts = generateHooksDts(["GameHooks"], "../../src/hooks");
    expect(dts).toContain("Auto-generated by @gwenjs/vite");
  });

  it("imports InferHooks from @gwenjs/core", () => {
    const dts = generateHooksDts(["GameHooks"], "../../src/hooks");
    expect(dts).toContain("import type { InferHooks } from '@gwenjs/core'");
  });

  it("imports all export names from the given importPath", () => {
    const dts = generateHooksDts(["GameHooks", "UIHooks"], "../../src/hooks");
    expect(dts).toContain("import type { GameHooks, UIHooks } from '../../src/hooks'");
  });

  it("augments GwenRuntimeHooks with InferHooks for a single export", () => {
    const dts = generateHooksDts(["GameHooks"], "../../src/hooks");
    expect(dts).toContain("declare module '@gwenjs/schema'");
    expect(dts).toContain("interface GwenRuntimeHooks extends InferHooks<typeof GameHooks>");
  });

  it("extends multiple InferHooks for multiple exports", () => {
    const dts = generateHooksDts(["GameHooks", "UIHooks"], "../../src/hooks");
    expect(dts).toContain("InferHooks<typeof GameHooks>, InferHooks<typeof UIHooks>");
  });

  it("output ends with a newline", () => {
    const dts = generateHooksDts(["GameHooks"], "../../src/hooks");
    expect(dts.endsWith("\n")).toBe(true);
  });
});
