name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}

      - uses: dtolnay/rust-toolchain@stable
        if: ${{ steps.release.outputs.releases_created }}
        with:
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        if: ${{ steps.release.outputs.releases_created }}
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - uses: ./.github/actions/setup-node-pnpm
        if: ${{ steps.release.outputs.releases_created }}

      - name: Build WASM
        if: ${{ steps.release.outputs.releases_created }}
        run: pnpm build:wasm

      - name: Build
        if: ${{ steps.release.outputs.releases_created }}
        run: pnpm build:ts

      - name: Publish to npm
        if: ${{ steps.release.outputs.releases_created }}
        run: pnpm -r publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
