/** Error codes emitted by the GWEN Physics3D plugin. */
export const Physics3DErrorCodes = {
  BVH_WORKER_TIMEOUT: "PHYSICS3D:BVH_WORKER_TIMEOUT",
  BVH_CALLBACK_HANG: "PHYSICS3D:BVH_CALLBACK_HANG",
  MESH_FALLBACK: "PHYSICS3D:MESH_FALLBACK",
  CONVEX_FALLBACK: "PHYSICS3D:CONVEX_FALLBACK",
  /** Entity id is not alive. */
  STALE_ENTITY: "PHYSICS3D:STALE_ENTITY",
  UNKNOWN_LAYER: "PHYSICS3D:UNKNOWN_LAYER",
  INVALID_COMPOUND: "PHYSICS3D:INVALID_COMPOUND",
  BVH_LOAD_FAILED: "PHYSICS3D:BVH_LOAD_FAILED",
  NOT_INITIALIZED: "PHYSICS3D:NOT_INITIALIZED",
  WASM_VARIANT_MISMATCH: "PHYSICS3D:WASM_VARIANT_MISMATCH",
  INVALID_MESH_BUFFER: "PHYSICS3D:INVALID_MESH_BUFFER",
  NO_RIGID_BODY: "PHYSICS3D:NO_RIGID_BODY",
  MESH_REBUILD_FAILED: "PHYSICS3D:MESH_REBUILD_FAILED",
} as const;

/** Type of a Physics3D error code string. */
export type Physics3DErrorCode = (typeof Physics3DErrorCodes)[keyof typeof Physics3DErrorCodes];
